### ISSUE TITLE
Adding symmetric difference

### ISSUE THREAD

**Issue by pevnak** [bottine/StaticBitSets.jl#5]
Would it make sense to add a symmetric difference?
Like 
```julia
@inline function Base.symdiff(s1::SBitSet{N,T},s2::SBitSet{N,T}) where {N,T<:Unsigned}
    SBitSet{N,T}(xor.(s1.pieces,s2.pieces))
end
```

Would you accept PR?

**Comment by bottine** [comment]
Hi, thanks for the comment!
I'm not up-to-date with julia, but I assume it would be natural to add `symdiff`, indeed. Gladly a PR then.

**Edit**: Well, I've just added it, since it's a simple addition. Closing the issue, I hope it provides what you need ?
